export const US_STATES_DATA = [
    { state: "Alabama", searchTerm: "600 Dexter ", optionText: "600 Dexter Avenue, Montgomery, AL, USA" },
    { state: "Alaska", searchTerm: "120 4th ", optionText: "120 4th Street, Juneau, AK, USA" },
    { state: "Arizona", searchTerm: "1700 W Washington ", optionText: "1700 W Washington Street, Phoenix, AZ, USA" },
    { state: "Arkansas", searchTerm: "500 Woodlane ", optionText: "500 Woodlane Street, Little Rock, AR, USA" },
    { state: "California", searchTerm: "1315 10th ", optionText: "1315 10th Street, Sacramento, CA, USA" },
    { state: "Colorado", searchTerm: "200 E Colfax ", optionText: "200 E Colfax Avenue, Denver, CO, USA" },
    { state: "Connecticut", searchTerm: "210 Capitol ", optionText: "210 Capitol Avenue, Hartford, CT, USA" },
    { state: "Delaware", searchTerm: "411 Legislative ", optionText: "411 Legislative Avenue, Dover, DE, USA" },
    { state: "Florida", searchTerm: "400 S Monroe ", optionText: "400 S Monroe Street, Tallahassee, FL, USA" },
    { state: "Georgia", searchTerm: "206 Washington ", optionText: "206 Washington Street SW, Atlanta, GA, USA" },
    { state: "Hawaii", searchTerm: "415 S Beretania ", optionText: "415 S Beretania Street, Honolulu, HI, USA" },
    { state: "Idaho", searchTerm: "700 W Jefferson ", optionText: "700 W Jefferson Street, Boise, ID, USA" },
    { state: "Illinois", searchTerm: "401 S 2nd ", optionText: "401 S 2nd Street, Springfield, IL, USA" },
    { state: "Indiana", searchTerm: "200 W Washington ", optionText: "200 W Washington Street, Indianapolis, IN, USA" },
    { state: "Iowa", searchTerm: "1007 E Grand ", optionText: "1007 E Grand Avenue, Des Moines, IA, USA" },
    { state: "Kansas", searchTerm: "300 SW 10th ", optionText: "300 SW 10th Avenue, Topeka, KS, USA" },
    { state: "Kentucky", searchTerm: "700 Capital ", optionText: "700 Capital Avenue, Frankfort, KY, USA" },
    { state: "Louisiana", searchTerm: "900 N 3rd ", optionText: "900 N 3rd Street, Baton Rouge, LA, USA" },
    { state: "Maine", searchTerm: "210 State ", optionText: "210 State Street, Augusta, ME, USA" },
    { state: "Maryland", searchTerm: "100 State ", optionText: "100 State Circle, Annapolis, MD, USA" },
    { state: "Massachusetts", searchTerm: "24 Beacon ", optionText: "24 Beacon Street, Boston, MA, USA" },
    { state: "Michigan", searchTerm: "100 N Capitol ", optionText: "100 N Capitol Avenue, Lansing, MI, USA" },
    { state: "Minnesota", searchTerm: "75 Rev Dr Martin Luther King Jr ", optionText: "75 Rev Dr Martin Luther King Jr Blvd, St Paul, MN, USA" },
    { state: "Mississippi", searchTerm: "400 High ", optionText: "400 High Street, Jackson, MS, USA" },
    { state: "Missouri", searchTerm: "201 W Capitol ", optionText: "201 W Capitol Avenue, Jefferson City, MO, USA" },
    { state: "Montana", searchTerm: "1301 E 6th ", optionText: "1301 E 6th Avenue, Helena, MT, USA" },
    { state: "Nebraska", searchTerm: "1445 K ", optionText: "1445 K Street, Lincoln, NE, USA" },
    { state: "Nevada", searchTerm: "101 N Carson ", optionText: "101 N Carson Street, Carson City, NV, USA" },
    { state: "New Hampshire", searchTerm: "107 N Main ", optionText: "107 N Main Street, Concord, NH, USA" },
    { state: "New Jersey", searchTerm: "125 W State ", optionText: "125 W State Street, Trenton, NJ, USA" },
    { state: "New Mexico", searchTerm: "490 Old Santa Fe ", optionText: "490 Old Santa Fe Trail, Santa Fe, NM, USA" },
    { state: "New York", searchTerm: "State St and Washington ", optionText: "State St and Washington Ave, Albany, NY, USA" },
    { state: "North Carolina", searchTerm: "1 E Edenton ", optionText: "1 E Edenton Street, Raleigh, NC, USA" },
    { state: "North Dakota", searchTerm: "600 E Boulevard ", optionText: "600 E Boulevard Avenue, Bismarck, ND, USA" },
    { state: "Ohio", searchTerm: "1 Capitol ", optionText: "1 Capitol Square, Columbus, OH, USA" },
    { state: "Oklahoma", searchTerm: "2300 N Lincoln ", optionText: "2300 N Lincoln Blvd, Oklahoma City, OK, USA" },
    { state: "Oregon", searchTerm: "900 Court ", optionText: "900 Court Street NE, Salem, OR, USA" },
    { state: "Pennsylvania", searchTerm: "501 N 3rd ", optionText: "501 N 3rd Street, Harrisburg, PA, USA" },
    { state: "Rhode Island", searchTerm: "82 Smith ", optionText: "82 Smith Street, Providence, RI, USA" },
    { state: "South Carolina", searchTerm: "1100 Gervais ", optionText: "1100 Gervais Street, Columbia, SC, USA" },
    { state: "South Dakota", searchTerm: "500 E Capitol ", optionText: "500 E Capitol Avenue, Pierre, SD, USA" },
    { state: "Tennessee", searchTerm: "600 Dr. M.L.K. Jr ", optionText: "600 Dr. M.L.K. Jr Blvd, Nashville, TN, USA" },
    { state: "Texas", searchTerm: "1100 Congress ", optionText: "1100 Congress Avenue, Austin, TX, USA" },
    { state: "Utah", searchTerm: "350 State ", optionText: "350 State Street, Salt Lake City, UT, USA" },
    { state: "Vermont", searchTerm: "115 State ", optionText: "115 State Street, Montpelier, VT, USA" },
    { state: "Virginia", searchTerm: "1000 Bank ", optionText: "1000 Bank Street, Richmond, VA, USA" },
    { state: "Washington", searchTerm: "416 Sid Snyder ", optionText: "416 Sid Snyder Highway SW, Olympia, WA, USA" },
    { state: "West Virginia", searchTerm: "1900 Kanawha ", optionText: "1900 Kanawha Blvd E, Charleston, WV, USA" },
    { state: "Wisconsin", searchTerm: "2 E Main ", optionText: "2 E Main Street, Madison, WI, USA" },
    { state: "Wyoming", searchTerm: "200 W 24th ", optionText: "200 W 24th Street, Cheyenne, WY, USA" }
];
